#!/bin/bash
# KODA Repository Initializer
# Creates a KODA-compliant repository structure
# Usage: ./koda-init.sh <namespace> [--type commercial|institutional|personal]

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
NAMESPACE=""
TYPE="commercial"
OWNER=""
EMAIL=""
DESCRIPTION=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --type)
            TYPE="$2"
            shift 2
            ;;
        --owner)
            OWNER="$2"
            shift 2
            ;;
        --email)
            EMAIL="$2"
            shift 2
            ;;
        --description)
            DESCRIPTION="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: koda-init.sh <namespace> [options]"
            echo ""
            echo "Options:"
            echo "  --type        Type: commercial|institutional|personal|opensource (default: commercial)"
            echo "  --owner       Organization/owner name"
            echo "  --email       Maintainer email"
            echo "  --description Brief description"
            echo ""
            echo "Example:"
            echo "  ./koda-init.sh acme --type commercial --owner 'ACME Corp' --email admin@acme.com"
            exit 0
            ;;
        *)
            NAMESPACE="$1"
            shift
            ;;
    esac
done

# Validate namespace
if [ -z "$NAMESPACE" ]; then
    echo -e "${RED}Error: Namespace is required${NC}"
    echo "Usage: koda-init.sh <namespace> [--type commercial|institutional|personal]"
    exit 1
fi

# Validate namespace format (lowercase, alphanumeric, hyphens)
if ! [[ "$NAMESPACE" =~ ^[a-z][a-z0-9-]*$ ]]; then
    echo -e "${RED}Error: Namespace must be lowercase, start with a letter, and contain only letters, numbers, and hyphens${NC}"
    exit 1
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║           KODA Repository Initializer                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Namespace: ${GREEN}$NAMESPACE${NC}"
echo -e "Type: ${GREEN}$TYPE${NC}"
echo ""

# Create directory structure
echo -e "${YELLOW}Creating directory structure...${NC}"
mkdir -p knowledge/core
mkdir -p knowledge/domains
mkdir -p agents
mkdir -p schemas
mkdir -p catalog
mkdir -p sources
mkdir -p staging
mkdir -p .github/workflows

echo -e "  ${GREEN}✓${NC} knowledge/core/"
echo -e "  ${GREEN}✓${NC} knowledge/domains/"
echo -e "  ${GREEN}✓${NC} agents/"
echo -e "  ${GREEN}✓${NC} schemas/"
echo -e "  ${GREEN}✓${NC} catalog/"
echo -e "  ${GREEN}✓${NC} sources/"
echo -e "  ${GREEN}✓${NC} staging/"
echo -e "  ${GREEN}✓${NC} .github/workflows/"

# Get current date
DATE=$(date +%Y-%m-%d)
DATETIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Create .knowledge-resolver.yml
echo -e "${YELLOW}Creating .knowledge-resolver.yml...${NC}"
cat > .knowledge-resolver.yml << EOF
# ${NAMESPACE} Knowledge Resolver
# KODA-compliant resolver configuration
# Generated by koda-init.sh on ${DATE}

_meta:
  resolver_version: "1.0.0"
  koda_compatibility: ">=1.0.0 <2.0.0"
  last_sync: "${DATETIME}"
  health_check_interval: weekly

self:
  namespace: "${NAMESPACE}"
  repository: "github.com/${OWNER:-your-org}/${NAMESPACE}"
  visibility: public
  maintainer: "${EMAIL:-maintainer@example.com}"

namespaces:
  ${NAMESPACE}:
    type: local
    base_path: "./"
    required: true
    description: "${DESCRIPTION:-${NAMESPACE} knowledge base}"
  
  koda:
    type: upstream
    base_path: "../koda/"
    fallback: "https://raw.githubusercontent.com/felix-antonio-sl/koda/main/"
    required: true
    description: "KODA Framework - upstream dependency"

resolution_rules:
  # Add your resolution rules here
  # "urn:knowledge:${NAMESPACE}:{domain}:{artifact}:*": "./{path}"

directories:
  knowledge: "./knowledge/"
  agents: "./agents/"
  catalog: "./catalog/"
  staging: "./staging/"
  sources: "./sources/"

cache:
  enabled: true
  ttl_seconds: 86400
EOF
echo -e "  ${GREEN}✓${NC} .knowledge-resolver.yml"

# Create catalog
echo -e "${YELLOW}Creating catalog...${NC}"
cat > catalog/catalog_master_${NAMESPACE}.yml << EOF
# ${NAMESPACE} Knowledge Catalog
# Master inventory of all artifacts
# Generated by koda-init.sh on ${DATE}

_manifest:
  urn: "urn:knowledge:${NAMESPACE}:catalog:master:1.0.0"
  federation:
    visibility: public
    license: "CC-BY-4.0"
  provenance:
    created_by: "${OWNER:-unknown}"
    created_at: "${DATE}"

Catalog:
  Core_Guides: []
    # Add your core guides here
    # - urn: "urn:knowledge:${NAMESPACE}:core:example:1.0.0"
    #   title: "Example Guide"
    #   file: "knowledge/core/guide_core_001_example_${NAMESPACE}.yml"
    #   status: draft

  Agents: []
    # Add your agents here

  Schemas: []
    # Add your schemas here

  Domains: []
    # Add domain-specific knowledge here

Statistics:
  total_artifacts: 0
  core_guides: 0
  agents: 0
  schemas: 0
  domains: 0
  last_updated: "${DATE}"
EOF
echo -e "  ${GREEN}✓${NC} catalog/catalog_master_${NAMESPACE}.yml"

# Create .gitignore
echo -e "${YELLOW}Creating .gitignore...${NC}"
cat > .gitignore << EOF
# Staging (work in progress)
staging/*
!staging/.gitkeep

# OS files
.DS_Store
Thumbs.db

# Python
*.pyc
__pycache__/
.venv/
venv/

# IDE
.idea/
*.swp
*.swo

# Logs
*.log

# Temp files
*.tmp
*.bak
EOF
echo -e "  ${GREEN}✓${NC} .gitignore"

# Create staging/.gitkeep
touch staging/.gitkeep
echo -e "  ${GREEN}✓${NC} staging/.gitkeep"

# Create README.md
echo -e "${YELLOW}Creating README.md...${NC}"
cat > README.md << EOF
# ${NAMESPACE}

[![KODA Compliant](https://img.shields.io/badge/KODA-Compliant-blue)](https://github.com/felix-antonio-sl/koda)

> ${DESCRIPTION:-Knowledge base for ${NAMESPACE}}

## Structure

\`\`\`
${NAMESPACE}/
├── knowledge/
│   ├── core/           # Core guides and specifications
│   └── domains/        # Domain-specific knowledge
├── agents/             # Agent definitions
├── schemas/            # JSON schemas
├── catalog/            # Artifact inventory
├── sources/            # Raw source materials
└── staging/            # Work in progress
\`\`\`

## URN Namespace

All artifacts use the namespace: \`${NAMESPACE}\`

Example URN: \`urn:knowledge:${NAMESPACE}:core:example:1.0.0\`

## Getting Started

1. Add knowledge artifacts to \`knowledge/\`
2. Register them in \`catalog/catalog_master_${NAMESPACE}.yml\`
3. Add resolution rules to \`.knowledge-resolver.yml\`

## Federation

This repository is part of the [KODA Federation](https://github.com/felix-antonio-sl/koda).

---

*Built with [KODA Framework](https://github.com/felix-antonio-sl/koda) — Knowledge-Oriented Design Architecture*
EOF
echo -e "  ${GREEN}✓${NC} README.md"

# Summary
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           KODA Repository Initialized!                     ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Next steps:"
echo -e "  1. ${YELLOW}git init${NC} (if not already a git repo)"
echo -e "  2. Update ${YELLOW}.knowledge-resolver.yml${NC} with your repository URL"
echo -e "  3. Create your first artifact in ${YELLOW}knowledge/core/${NC}"
echo -e "  4. Register at ${YELLOW}https://github.com/felix-antonio-sl/koda${NC} (optional)"
echo ""
echo -e "Validate with:"
echo -e "  ${BLUE}./scripts/koda-validate.sh${NC}"
echo ""
